### ISSUE TITLE
Unable to find image 'aangeloo/ont-guppy:4.0.14' locally

### ISSUE THREAD

**Issue by Vikash84** [angelovangel/nxf-ont#6]
Command exit status:
  125

Command output:
  (empty)

Command error:
  Unable to find image 'aangeloo/ont-guppy:4.0.14' locally
  docker: Error response from daemon: pull access denied for aangeloo/ont-guppy, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
  See 'docker run --help'.

**Comment by angelovangel** [comment]
Dear Vikash84, currently we are not allowed to re-distribute the guppy docker image, so it is in a private docker repo. You can build your own however, using the provided docker files. After that, you can point to the newly built image in the nextflow configuration file.

**Comment by Vikash84** [comment]
Thanks Angel for your kind reply.

**Comment by angelovangel** [comment]
Pleas let me know if that worked for you so I can close the issue...
